version: '3.8'

services:
  test-db:
    image: mongo
    ports:
      - "3051:8081"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - test-db-data:/data/db  # Only use the volume for MongoDB
    networks:
      - test-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "30578:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@test-db:27017/
    networks:
      - test-network

volumes:
  test-db-data:  # Define the volume here for persistence

networks:
  test-network:
    driver: bridge
